#!/bin/sh
#
# zarafa4ucs machine.secret
#
# Copyright 2012-2016 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

eval "$(univention-config-registry shell)"

if [ "$1" = "postchange" -o "$1" = "nochange" ] ; then

	# copy machine.secret
	dest="/etc/zarafa-ldap.secret"
	cp /etc/machine.secret "$dest"
	chown root:root "$dest"
	chmod 600  "$dest"

	# commit changes
	univention-config-registry set zarafa/cfg/ldap/ldap_bind_passwd="$zarafa_cfg_ldap_ldap_bind_passwd"

	# if multiserver support is installed, change password accordingly in ldapms.cfg
	if dpkg-query --show --showformat='${Status}\n' "zarafa4ucs-multiserver" | grep -qs "install ok installed"; then
		ucr set zarafa/cfg/ldapms/ldap_bind_passwd="$zarafa_cfg_ldapms_ldap_bind_passwd"
	fi

	# according to the manual reloading is sufficient for ldap configuration changes
	#   "After the LDAP configuration is done, the changes can 
	#   be activated by reloading the Zarafa Server."
	# no, see Bug #31709
	/etc/init.d/zarafa-server restart

fi	
